# Generated by Django 5.2.5 on 2025-09-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishbook', '0002_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_on',
            field=models.DateTimeField(blank=True, max_length=256, null=True),
        ),
    ]
