# Generated by Django 5.2.5 on 2025-09-26 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishbook', '0003_alter_recipe_featured_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='dishbook.recipe'),
        ),
    ]
