# Generated by Django 5.2.5 on 2025-10-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishbook', '0004_alter_recipe_copied_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time_minutes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(),
        ),
    ]
