# Generated by Django 5.2.5 on 2025-10-25 00:05

import dishbook.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishbook', '0005_alter_recipe_cook_time_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(validators=[dishbook.models.reject_zero_or_negative_float]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, validators=[dishbook.models.reject_non_standard_string]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='dishbook.step'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=16, validators=[dishbook.models.reject_non_standard_string]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(validators=[dishbook.models.reject_non_standard_string]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=64, validators=[dishbook.models.reject_non_standard_string]),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(validators=[dishbook.models.reject_non_standard_string]),
        ),
    ]
