# Generated by Django 5.2.5 on 2025-11-04 18:13

import dishbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishbook', '0006_alter_ingredient_amount_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.PositiveIntegerField(validators=[dishbook.models.reject_zero]),
        ),
    ]
