# Generated by Django 5.2.5 on 2025-11-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishbook', '0007_alter_recipe_serves'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
