# Generated by Django 5.2.5 on 2025-11-06 19:02

import dishbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishbook', '0008_recipe_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', validators=[dishbook.models.reject_big_files]),
        ),
    ]
